### PR TITLE
Added Input generation function for gpt

### PR DESCRIPTION
**Pull request by abhilashreddyy**

### CODE REVIEW

**Comment by kurbster** [comment]
Can you create a script that will call the GPT API?

**Comment by kurbster** [comment]
Just curious what you put in the environ folder. On my branch _kirby_ I added a .env folder that has the API keys stored in a file like this. `export OPENAI_API_KEY=1234...` so then you can just run `. api_key_file` then your environment will have that variable saved.

**Comment by abhilashreddyy** [comment]
Hey I am unable to see environ folder on my forked repo. Might be a mistake.

chek [here](https://github.com/abhilashreddyy/Prompt-Summarization)

**Comment by kurbster** [comment]
You put it in your .gitignore so its not on git. But what did you put there on your local machine.

**Comment by abhilashreddyy** [comment]
I used to keep it but now I have removed it

**Pull request merged**
